version: '3.4'

services:
  dockergigapi:
    links:  
      - sqlserver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  sqlserver:  
    image: microsoft/mssql-server-linux:2017-latest
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: Y  
      SA_PASSWORD: "2Secure*Password2" 
    ports:  
      - '1433:1433'
    expose:
      - 1433